services:
  - type: web
    name: qota-finance-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: qota-finance-db
          property: connectionString
      - key: PORT
        value: 8000
