import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DragDropModule } from '@angular/cdk/drag-drop';
import { KanbanBoardComponent } from './components/kanban-board/kanban-board.component';
import {
  LucideAngularModule,
  Home,
  DollarSign,
  TrendingUp,
  CreditCard,
  Package,
  Lock,
  Key,
  Building2,
  Eye,
  EyeOff,
  Copy,
  Edit,
  Trash2,
  Plus,
  X,
  Search,
  Save,
  ChevronDown,
  Calendar,
  ExternalLink,
  RefreshCw,
  BarChart3,
  PieChart,
  ShoppingCart,
  ShoppingBag,
  Wallet,
  Target,
  Filter,
  Download,
  Upload,
  FileText,
  CheckCircle,
  AlertCircle,
  Info,
  Zap,
  TrendingDown,
  Activity,
  DollarSign as Money,
  Receipt,
  MapPin,
  Phone,
  Mail,
  Globe,
  User,
  Users,
  Settings,
  Menu,
  MoreVertical
} from 'lucide-angular';

@NgModule({
  declarations: [
    KanbanBoardComponent
  ],
  imports: [
    CommonModule,
    DragDropModule,
    LucideAngularModule.pick({
      Home,
      DollarSign,
      TrendingUp,
      CreditCard,
      Package,
      Lock,
      Key,
      Building2,
      Eye,
      EyeOff,
      Copy,
      Edit,
      Trash2,
      Plus,
      X,
      Search,
      Save,
      ChevronDown,
      Calendar,
      ExternalLink,
      RefreshCw,
      BarChart3,
      PieChart,
      ShoppingCart,
      ShoppingBag,
      Wallet,
      Target,
      Filter,
      Download,
      Upload,
      FileText,
      CheckCircle,
      AlertCircle,
      Info,
      Zap,
      TrendingDown,
      Activity,
      Money,
      Receipt,
      MapPin,
      Phone,
      Mail,
      Globe,
      User,
      Users,
      Settings,
      Menu,
      MoreVertical
    })
  ],
  exports: [
    KanbanBoardComponent,
    LucideAngularModule
  ]
})
export class SharedModule { }
